version: "3.7"
services:
  app:
    build:
      context: .
    container_name: app
    working_dir: /app
    command: bash
    tty: true
    env_file:
      - .env.prd
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    # depends_on:
    #   - postgres
  # postgres:
  #   image: postgres:12.3-alpine
  #   container_name: postgres
  #   env_file:
  #     - .env
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local