[config]
skip_core_tasks = true

[tasks.test-watch]
watch = { watch = ["src"] }
run_task = "test"

[tasks.run]
env_files = [
  ".env",
]
command = "cargo"
args = ["run"]

[tasks.test]
command = "cargo"
args = ["test", "--", "--nocapture", "-q"]

[tasks.migrate]
env_files = [
  ".env.prd",
]
command = "psqldef"
args = [
  "-U", "${POSTGRES_USER}",
  "-W", "${POSTGRES_PASSWORD}",
  "-p", "${POSTGRES_PORT}",
  "-h", "${POSTGRES_HOST}",
  "-f", "schema.sql",
  "${POSTGRES_DB}",
]